# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'campus-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for campus-app
  pod 'AWSMobileClient'
  pod 'AWSAuthUI'
  pod 'AWSUserPoolsSignIn'
  pod 'AWSS3'
  pod 'AWSDynamoDB'
  pod 'AWSAppSync'
  pod 'Amplify'
  pod 'SwiftyTesseract', '~> 2.0'
end
